version: '3.8'
services:
    php-apache-environment:
        container_name: sqli-challenge
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./src:/var/www/html/
        ports:
            - 2408:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 't357_p4ssw0rd'
            MYSQL_DATABASE: 'hackershala'
            MYSQL_USER: 'admin'
            MYSQL_PASSWORD: 't357_p4ssw0rd'
        ports:
            - "9906:3306"
